name: Java CD

on: 
  release:
    types: published

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy to Bintray
      id: deploy-to-bintray
      run: mvn deploy -s .github/bintray-settings.xml || echo "deploy failed"
      env:
        BINTRAY_USERNAME: ${{secrets.bintray_username}}
        BINTRAY_PASSWORD: ${{secrets.bintray_password}}
    - name: Attach files to Release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/kotlin-pandoc-*.jar
        asset_name: kotlin-pandoc-*.jar
